# Generated by Django 6.0.5 on 2026-06-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_session_qr_token_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="attendance_radius_meters",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="session",
            name="location_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="location_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="qr_session_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
