# Generated by Django 6.0.5 on 2026-07-03 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_session_module"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="teacher",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    ("role", "teacher"),
                    models.Q(("is_also_teacher", True), ("role", "admin")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
