# Generated by Django 6.0.5 on 2026-07-06 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_session_session_type"),
        ("users", "0009_fix_legacy_classe_columns_sql"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sessions",
                to="users.module",
                verbose_name="Module",
            ),
        ),
    ]
