# Generated by Django 5.1.4 on 2026-05-10 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='users.student'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'session')},
        ),
    ]
