# Generated by Django 6.0.5 on 2026-06-03 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_initial"),
        ("courses", "0005_session_attendance_radius_meters_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="attendance_status",
            field=models.CharField(
                choices=[("confirmed", "Confirmed"), ("rejected", "Rejected")],
                default="confirmed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="device_fingerprint",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="attendance",
            name="device_info",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="attendance",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="attendance",
            name="qr_session_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.CreateModel(
            name="SuspiciousAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_type",
                    models.CharField(
                        choices=[
                            ("duplicate_student", "Duplicate student"),
                            ("duplicate_device", "Duplicate device"),
                            ("geofence_violation", "Geofence violation"),
                            ("expired_qr", "Expired QR"),
                            ("invalid_token", "Invalid token"),
                            ("inactive_session", "Inactive session"),
                            ("identity_mismatch", "Identity mismatch"),
                            ("class_mismatch", "Class mismatch"),
                            ("unknown_student", "Unknown student"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("qr_token", models.CharField(blank=True, default="", max_length=100)),
                (
                    "qr_session_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "code_massar",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("last_name", models.CharField(blank=True, default="", max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("device_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "device_fingerprint",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("device_info", models.TextField(blank=True, default="")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("error_message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suspicious_attempts",
                        to="courses.session",
                    ),
                ),
            ],
            options={
                "db_table": "suspicious_attempts",
                "ordering": ["-created_at"],
            },
        ),
    ]
