# Generated by Django 5.1.6 on 2026-07-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_student_classe_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_also_teacher",
            field=models.BooleanField(
                default=False,
                help_text="Si coché, un administrateur peut aussi agir comme enseignant.",
            ),
        ),
    ]
